use keymap::Key;
use windows::Win32::UI::Input::KeyboardAndMouse::*;

pub fn vk_to_key(vk: u16) -> Option<Key> {
    match VIRTUAL_KEY(vk) {
        VK_OEM_3 => Some(Key::Backquote),
        VK_1 => Some(Key::Digit1),
        VK_2 => Some(Key::Digit2),
        VK_3 => Some(Key::Digit3),
        VK_4 => Some(Key::Digit4),
        VK_5 => Some(Key::Digit5),
        VK_6 => Some(Key::Digit6),
        VK_7 => Some(Key::Digit7),
        VK_8 => Some(Key::Digit8),
        VK_9 => Some(Key::Digit9),
        VK_0 => Some(Key::Digit0),
        VK_OEM_MINUS => Some(Key::Minus),
        VK_OEM_PLUS => Some(Key::Equal),
        VK_Q => Some(Key::KeyQ),
        VK_W => Some(Key::KeyW),
        VK_E => Some(Key::KeyE),
        VK_R => Some(Key::KeyR),
        VK_T => Some(Key::KeyT),
        VK_Y => Some(Key::KeyY),
        VK_U => Some(Key::KeyU),
        VK_I => Some(Key::KeyI),
        VK_O => Some(Key::KeyO),
        VK_P => Some(Key::KeyP),
        VK_OEM_4 => Some(Key::BracketLeft),
        VK_OEM_6 => Some(Key::BracketRight),
        VK_OEM_5 => Some(Key::Backslash),
        VK_A => Some(Key::KeyA),
        VK_S => Some(Key::KeyS),
        VK_D => Some(Key::KeyD),
        VK_F => Some(Key::KeyF),
        VK_G => Some(Key::KeyG),
        VK_H => Some(Key::KeyH),
        VK_J => Some(Key::KeyJ),
        VK_K => Some(Key::KeyK),
        VK_L => Some(Key::KeyL),
        VK_OEM_1 => Some(Key::Semicolon),
        VK_OEM_7 => Some(Key::Quote),
        VK_Z => Some(Key::KeyZ),
        VK_X => Some(Key::KeyX),
        VK_C => Some(Key::KeyC),
        VK_V => Some(Key::KeyV),
        VK_B => Some(Key::KeyB),
        VK_N => Some(Key::KeyN),
        VK_M => Some(Key::KeyM),
        VK_OEM_COMMA => Some(Key::Comma),
        VK_OEM_PERIOD => Some(Key::Period),
        VK_OEM_2 => Some(Key::Slash),
        _ => None,
    }
}
