use keymap::Key;

pub fn mac_keycode_to_key(keycode: u16) -> Option<Key> {
    // macOS Virtual Keycodes mapping to W3C keys.
    match keycode {
        50 => Some(Key::Backquote),
        18 => Some(Key::Digit1),
        19 => Some(Key::Digit2),
        20 => Some(Key::Digit3),
        21 => Some(Key::Digit4),
        23 => Some(Key::Digit5),
        22 => Some(Key::Digit6),
        26 => Some(Key::Digit7),
        28 => Some(Key::Digit8),
        25 => Some(Key::Digit9),
        29 => Some(Key::Digit0),
        27 => Some(Key::Minus),
        24 => Some(Key::Equal),
        12 => Some(Key::KeyQ),
        13 => Some(Key::KeyW),
        14 => Some(Key::KeyE),
        15 => Some(Key::KeyR),
        17 => Some(Key::KeyT),
        16 => Some(Key::KeyY),
        32 => Some(Key::KeyU),
        34 => Some(Key::KeyI),
        31 => Some(Key::KeyO),
        35 => Some(Key::KeyP),
        33 => Some(Key::BracketLeft),
        30 => Some(Key::BracketRight),
        42 => Some(Key::Backslash),
        0 => Some(Key::KeyA),
        1 => Some(Key::KeyS),
        2 => Some(Key::KeyD),
        3 => Some(Key::KeyF),
        5 => Some(Key::KeyG),
        4 => Some(Key::KeyH),
        38 => Some(Key::KeyJ),
        40 => Some(Key::KeyK),
        37 => Some(Key::KeyL),
        41 => Some(Key::Semicolon),
        39 => Some(Key::Quote),
        6 => Some(Key::KeyZ),
        7 => Some(Key::KeyX),
        8 => Some(Key::KeyC),
        9 => Some(Key::KeyV),
        11 => Some(Key::KeyB),
        45 => Some(Key::KeyN),
        46 => Some(Key::KeyM),
        43 => Some(Key::Comma),
        47 => Some(Key::Period),
        44 => Some(Key::Slash),
        _ => None,
    }
}
